---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: "echo-${sha}"
    app.kubernetes.io/version: "${sha}"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: "${NAME}"
    app.kubernetes.io/managed-by: none
  annotations:
    app.kubernetes.io/timestamp: "${TS}"
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      containers:
        - name: echo
          image: docker.io/alpine/socat:1.7.4.3-r1
          args:
            - "-v"
            - "-T1"
            - "tcp-l:${portecho},reuseaddr,fork"
            - "system:cat"
          ports:
            - containerPort: ${portecho}
              name: main
          livenessProbe:
            tcpSocket:
              port: main
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: main
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: "echo-${sha}"
    app.kubernetes.io/version: "${sha}"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: "${NAME}"
    app.kubernetes.io/managed-by: none
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: echo
  ports:
    - port: ${portecho}
      targetPort: main
