---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripseven
  labels:
    app.kubernetes.io/name: stripseven
    app.kubernetes.io/instance: "stripseven-${sha}"
    app.kubernetes.io/version: "${sha}"
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: "${NAME}"
    app.kubernetes.io/managed-by: none
  annotations:
    app.kubernetes.io/timestamp: "${TS}"
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: stripseven
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stripseven
    spec:
      containers:
        - name: stripseven
          image: docker.io/christianelsee/stripseven:${sha}
          args:
            - "run"
            - "--listen"
            - "0.0.0.0:80"
            - "--target"
            - "echo:${portecho}"
          ports:
            - containerPort: 80
              name: main
          livenessProbe:
            tcpSocket:
              port: main
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: main
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: stripseven
  labels:
    app.kubernetes.io/name: stripseven
    app.kubernetes.io/instance: "stripseven-${sha}"
    app.kubernetes.io/version: "${sha}"
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: "${NAME}"
    app.kubernetes.io/managed-by: none
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: stripseven
  ports:
    - port: 80
      targetPort: main
