name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # checkout repo
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3

      - name: Log git identifiers for build
        run: >
          logger -sp INFO -- "Start build" \
            "branch=$GITHUB_REF" \
            "sha=$GITHUB_SHA"

      - name: Build target
        run: make build

      - name: Check build target
        run: make check
